# Generated by Django 3.2.7 on 2021-11-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Telefono'),
        ),
    ]
